[project]
name = "hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyautogui>=0.9.54",
    "requests>=2.32.5",
    "opencv-python>=4.12.0.88",
    "earthengine-api>=1.7.9",
    "geemap>=0.36.6",
    "httplib2>=0.31.0",
    "python-dotenv>=1.2.1",
    "ipywidgets>=8.1.8",
    "jupyterlab-widgets>=3.0.16",
    "jupyter-leaflet>=0.20.0",
    "pandas>=2.3.3",
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
